### ISSUE TITLE
XT error in suma on debian with Cmake build

### ISSUE THREAD

**Issue by afni-dglen** [afni/afni#158] opened 2020-03-18 20:36 UTC
suma

suma: 
     No input specified, loading some toy surfaces...
     Use '.' and ',' to cycle between them.
     See suma -help for assistance.

oo     Warning SUMA_XErrHandler (/home/dglen/git_afni/AFNI/src/SUMA/SUMA_display.c:4149):
Intercepted X11 error: BadWindow (invalid Window parameter)
Will attempt to proceed but trouble might ensue.
++     Notice SUMA_XErrHandler (/home/dglen/git_afni/AFNI/src/SUMA/SUMA_display.c:4150 @16:33:01):
Trace At Xerr
    SUMA_XErrHandler
   SUMA_X_SurfaceViewer_Create
  suma
 Bottom of Debug Stack
oo     Warning SUMA_XErrHandler (/home/dglen/git_afni/AFNI/src/SUMA/SUMA_display.c:4149):
Intercepted X11 error: BadWindow (invalid Window parameter)
Will attempt to proceed but trouble might ensue.
++     Notice SUMA_XErrHandler (/home/dglen/git_afni/AFNI/src/SUMA/SUMA_display.c:4150 @16:33:01):
Trace At Xerr
    SUMA_XErrHandler
   SUMA_X_SurfaceViewer_Create
  suma
 Bottom of Debug Stack
oo     Warning SUMA_XErrHandler (/home/dglen/git_afni/AFNI/src/SUMA/SUMA_display.c:4149):
Intercepted X11 error: BadWindow (invalid Window parameter)
Will attempt to proceed but trouble might ensue.
++     Notice SUMA_XErrHandler (/home/dglen/git_afni/AFNI/src/SUMA/SUMA_display.c:4150 @16:33:01):
Trace At Xerr
    SUMA_XErrHandler
   SUMA_X_SurfaceViewer_Create
  suma
 Bottom of Debug Stack
Error: No realize class procedure defined

ldd `which suma`
	linux-vdso.so.1 (0x00007fffe3a4c000)
	libSUMA.so => /home/dglen/git_afni/afni_build/local_install_dir/usr/local/bin/../lib/libSUMA.so (0x00007fdbfc5dd000)
	libmrix.so => /home/dglen/git_afni/afni_build/local_install_dir/usr/local/bin/../lib/libmrix.so (0x00007fdbfc2d7000)
	libXt.so.6 => /usr/lib/x86_64-linux-gnu/libXt.so.6 (0x00007fdbfc06e000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fdbfbd36000)
	libmri.so => /home/dglen/git_afni/afni_build/local_install_dir/usr/local/bin/../lib/libmri.so (0x00007fdbfb179000)
	libOpenGL.so.0 => /usr/lib/x86_64-linux-gnu/libOpenGL.so.0 (0x00007fdbfaf4b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdbfab5a000)
	libGLw.so.1 => /usr/lib/x86_64-linux-gnu/libGLw.so.1 (0x00007fdbfa953000)
	libXm.so.4 => /usr/lib/x86_64-linux-gnu/libXm.so.4 (0x00007fdbfa491000)
	libXmu.so.6 => /usr/lib/x86_64-linux-gnu/libXmu.so.6 (0x00007fdbfa278000)
	libglut.so.3 => /usr/lib/x86_64-linux-gnu/libglut.so.3 (0x00007fdbfa02f000)
	libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007fdbf9dc0000)
	libtrack_tools.so => /home/dglen/git_afni/afni_build/local_install_dir/usr/local/bin/../lib/libtrack_tools.so (0x00007fdbf9b87000)
	libsegtools.so => /home/dglen/git_afni/afni_build/local_install_dir/usr/local/bin/../lib/libsegtools.so (0x00007fdbf996d000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fdbf973c000)
	libcoxplot.so => /home/dglen/git_afni/afni_build/local_install_dir/usr/local/bin/../lib/libcoxplot.so (0x00007fdbf93ee000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdbf9050000)
	lib3DEdge.so => /home/dglen/git_afni/afni_build/local_install_dir/usr/local/bin/../lib/lib3DEdge.so (0x00007fdbf8e33000)
	libnifti2.so.2.8.8 => /home/dglen/git_afni/afni_build/local_install_dir/usr/local/bin/../lib/libnifti2.so.2.8.8 (0x00007fdbf8c03000)
	libXmHTML.so.1.1 => /usr/lib/x86_64-linux-gnu/libXmHTML.so.1.1 (0x00007fdbf8986000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007fdbf877e000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007fdbf8563000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fdbf833b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdbf8137000)
	libeispack.so => /home/dglen/git_afni/afni_build/local_install_dir/usr/local/bin/../lib/libeispack.so (0x00007fdbf7ef5000)
	libvolpack.so => /home/dglen/git_afni/afni_build/local_install_dir/usr/local/bin/../lib/libvolpack.so (0x00007fdbf7ca1000)
	libnifticdf.so.2.8.8 => /home/dglen/git_afni/afni_build/local_install_dir/usr/local/bin/../lib/libnifticdf.so.2.8.8 (0x00007fdbf7a80000)
	libnetcdf.so.13 => /usr/lib/x86_64-linux-gnu/libnetcdf.so.13 (0x00007fdbf775e000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fdbf7541000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fdbf728b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdbfd3db000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fdbf6fff000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fdbf6ded000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fdbf6ba8000)
	libXft.so.2 => /usr/lib/x86_64-linux-gnu/libXft.so.2 (0x00007fdbf6993000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fdbf672b000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fdbf64f9000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fdbf62e9000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fdbf60e3000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdbf5d5a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdbf5b42000)
	libgsl.so.23 => /usr/lib/x86_64-linux-gnu/libgsl.so.23 (0x00007fdbf56e0000)
	libgslcblas.so.0 => /usr/lib/x86_64-linux-gnu/libgslcblas.so.0 (0x00007fdbf54a1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdbf5282000)
	libznz.so.2.8.8 => /home/dglen/git_afni/afni_build/local_install_dir/usr/local/bin/../lib/../../../usr/local/lib/libznz.so.2.8.8 (0x00007fdbf507e000)
	libXpm.so.4 => /usr/lib/x86_64-linux-gnu/libXpm.so.4 (0x00007fdbf4e6c000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fdbf4c65000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fdbf4a50000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fdbf484c000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fdbf4646000)
	libhdf5_serial_hl.so.100 => /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so.100 (0x00007fdbf4423000)
	libhdf5_serial.so.100 => /usr/lib/x86_64-linux-gnu/libhdf5_serial.so.100 (0x00007fdbf3ecb000)
	libcurl-gnutls.so.4 => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007fdbf3c4e000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fdbf399a000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fdbf3768000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fdbf355e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdbf3356000)
	libsz.so.2 => /usr/lib/x86_64-linux-gnu/libsz.so.2 (0x00007fdbf3153000)
	libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007fdbf2f2e000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007fdbf2d11000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007fdbf2af5000)
	libpsl.so.5 => /usr/lib/x86_64-linux-gnu/libpsl.so.5 (0x00007fdbf28e7000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007fdbf26b1000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007fdbf234c000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fdbf2101000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007fdbf1eaf000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007fdbf1ca1000)
	libaec.so.0 => /usr/lib/x86_64-linux-gnu/libaec.so.0 (0x00007fdbf1a99000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007fdbf171b000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007fdbf14e7000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fdbf1266000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fdbf0f37000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fdbf0d24000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fdbf0a4e000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fdbf081c000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fdbf0618000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fdbf040d000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fdbf01f2000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007fdbeffd7000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007fdbefd96000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fdbefb8e000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fdbef98a000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007fdbef781000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007fdbef4f4000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007fdbef252000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007fdbef01c000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007fdbeee06000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007fdbeebdd000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007fdbee9ce000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007fdbee784000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fdbee47b000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fdbee243000)

**Comment by leej3** [comment] 2020-03-23 15:43
Looks like the same error as #131. I will confirm that it is indeed just a regression and add a build time check so that this can't happen again.

**Comment by leej3** [comment] 2020-06-15 17:57
I can't reproduce this on any system I have access to so I will close this for now

**Closed by leej3** 2020-06-15 17:57 UTC

**Comment by leej3** [comment] 2020-07-03 15:03
This is solved in #183. I can't figure out why my debian laptop did not have this issue at the time. But the container did have the issue. I didn't detect it because my test for suma wasn't working (massive failures but not error codes. My bad). I've added a compile time check for this so hopefully it never happens again.
